export const OFFER_CREATE_REQUEST = "OFFER_CREATE_REQUEST";
export const OFFER_CREATE_SUCCESS = "OFFER_CREATE_SUCCESS";
export const OFFER_CREATE_FAIL = "OFFER_CREATE_FAIL";
export const OFFER_CREATE_RESET = "OFFER_CREATE_RESET";
