export const PROVIDER_LIST_REQUEST = "PROVIDER_LIST_REQUEST";
export const PROVIDER_LIST_SUCCESS = "PROVIDER_LIST_SUCCESS";
export const PROVIDER_LIST_FAIL = "PROVIDER_LIST_FAIL";

export const PROVIDER_DATA_REQUEST = "PROVIDER_DATA_REQUEST";
export const PROVIDER_DATA_SUCCESS = "PROVIDER_DATA_SUCCESS";
export const PROVIDER_DATA_FAIL = "PROVIDER_DATA_FAIL";

export const PROVIDER_CREATE_REVIEW_REQUEST = "PROVIDER_CREATE_REVIEW_REQUEST";
export const PROVIDER_CREATE_REVIEW_SUCCESS = "PROVIDER_CREATE_REVIEW_SUCCESS";
export const PROVIDER_CREATE_REVIEW_FAIL = "PROVIDER_CREATE_REVIEW_FAIL";
export const PROVIDER_CREATE_REVIEW_RESET = "PROVIDER_CREATE_REVIEW_RESET";

export const PROVIDER_UPDATE_REQUEST = "PROVIDER_UPDATE_REQUEST";
export const PROVIDER_UPDATE_SUCCESS = "PROVIDER_UPDATE_SUCCESS";
export const PROVIDER_UPDATE_FAIL = "PROVIDER_UPDATE_FAIL";
export const PROVIDER_UPDATE_RESET = "PROVIDER_UPDATE_RESET";

export const PROVIDER_ADD_PROFESSION_REQUEST =
  "PROVIDER_ADD_PROFESSION_REQUEST";
export const PROVIDER_ADD_PROFESSION_SUCCESS =
  "PROVIDER_ADD_PROFESSION_SUCCESS";
export const PROVIDER_ADD_PROFESSION_FAIL = "PROVIDER_ADD_PROFESSION_FAIL";
export const PROVIDER_ADD_PROFESSION_RESET = "PROVIDER_ADD_PROFESSION_RESET";

export const PROVIDER_DELETE_PROFESSION_REQUEST =
  "PROVIDER_DELETE_PROFESSION_REQUEST";
export const PROVIDER_DELETE_PROFESSION_SUCCESS =
  "PROVIDER_DELETE_PROFESSION_SUCCESS";
export const PROVIDER_DELETE_PROFESSION_FAIL =
  "PROVIDER_DELETE_PROFESSION_FAIL";
export const PROVIDER_DELETE_PROFESSION_RESET =
  "PROVIDER_DELETE_PROFESSION_RESET";
