export const SEARCH_CITY_REQUEST = "SEARCH_CITY_REQUEST";
export const SEARCH_CITY_SUCCESS = "SEARCH_CITY_SUCCESS";
export const SEARCH_CITY_FAIL = "SEARCH_CITY_FAIL";

export const SEARCH_PROFESSION_REQUEST = "SEARCH_PROFESSION_REQUEST";
export const SEARCH_PROFESSION_SUCCESS = "SEARCH_PROFESSION_SUCCESS";
export const SEARCH_PROFESSION_FAIL = "SEARCH_PROFESSION_FAIL";

export const SEARCH_CATEGORY_REQUEST = "SEARCH_CATEGORY_REQUEST";
export const SEARCH_CATEGORY_SUCCESS = "SEARCH_CATEGORY_SUCCESS";
export const SEARCH_CATEGORY_FAIL = "SEARCH_CATEGORY_FAIL";
